export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
};

export default function Products() {
  return (
    <div>
      <h1>This is the products page</h1>
    </div>
  );
}
