import './globals.css';
import localFont from 'next/font/local';
import Footer from './components/Footer';
import Header from './components/Header';

export const metadata = {
  title: {
    default: 'Home | My Next Site',
    template: '%s | My Next Site',
  },
  description: 'Generated by create next app',
};

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
