import './globals.css';
import localFont from 'next/font/local';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: {
    default: 'Home | My Next Site',
    template: '%s | My Next Site',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="fixedHeader">
          <div className="headerContent">
            <h1 className="logo"> My Next Site</h1>
            <nav>
              <Link href="/" className="links">
                Home
              </Link>

              <Link href="/products" className="links">
                Products
              </Link>

              <Link href="/contact" className="links">
                Contact
              </Link>
            </nav>
          </div>
        </header>

        <main className="content"> {children}</main>
      </body>
    </html>
  );
}
