import React from 'react';

export const metadata = {
  title: 'Checkout',
  description: 'Generated by create next app',
};

export default function CheckoutPage() {
  return <div>CheckoutPage</div>;
}
