import Image from 'next/image';
import Link from 'next/link';
import { getBooksInsecure } from '../../database/books';

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
};

export default async function ProductsPage() {
  const books = await getBooksInsecure();

  return (
    <div className="container mx-auto p-4">
      <h1 className="text-3xl font-bold mb-6">Our Top Picks</h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {books.map((book) => (
          <div
            key={`books-${book.id}`}
            className="border rounded-lg p-4 shadow-lg"
          >
            <Link href={`/products/${book.id}`}>
              <div className="cursor-pointer">
                <Image
                  src={`/${book.urlname}.webp`}
                  alt={book.name}
                  width={200}
                  height={300}
                  className="rounded"
                />
                <h2 className="text-xl font-bold mt-2">{book.name}</h2>
                <h4 className="text-l font-bold mt-2">{book.author}</h4>

                <p className="text-gray-700 mt-1">{book.description}</p>
                <p className="text-lg font-bold mt-1">${book.price}</p>
              </div>
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
}
